### ISSUE TITLE
Bad credential not raised for these connectors

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#267] opened 2016-05-22 17:14 UTC
No call to next('bad credentials')
- [ ] ./googlecontacts.coffee
- [ ] ./sncf.js
- [ ] ./isen.coffee
- [ ] ./birthdays.js
- [ ] ./linkedin.js
- [ ] ./ovh_eu.coffee
- [ ] ./ovh_ca.coffee
- [ ] ./soyoustart_eu.coffee
- [ ] ./soyoustart_ca.coffee
- [ ] ./kimsufi_eu.coffee
- [ ] ./kimsufi_ca.coffee
- [ ] ./ical_feed.js
- [ ] ./github.coffee
- [ ] ./sfr_box.js
- [ ] ./sfr_mobile.js
- [ ] ./nest.coffee
- [ ] ./online_net.coffee
- [ ] ./runabove.coffee
- [ ] ./rescuetime.coffee
- [ ] ./digitalocean.coffee
- [ ] ./bouyguesbox.coffee
- [ ] ./bouyguestelecom.coffee
- [ ] ./orange.coffee
- [ ] ./sosh.coffee

**Comment by ZeHiro** [comment] 2016-05-22 17:42
Which means the user is not warned if he has not entered the right password

**Comment by nicofrand** [comment] 2016-07-20 14:00
Duplicate of Duplicate of https://github.com/cozy-labs/konnectors/issues/163 ?

**Comment by nicofrand** [comment] 2016-07-29 12:43
Some of the connectors return the error itself instead of "bad credentials". Ex: https://github.com/cozy-labs/konnectors/blob/master/server/konnectors/sfr_mobile.js#L94

Maybe the documentation isn't clear enough ?

**Comment by nicofrand** [comment] 2016-08-30 14:19
For Orange, see https://github.com/cozy-labs/konnectors/blob/master/server/konnectors/orange.coffee#L109

When wrong credentials are provided, a "password: null" field is returned.
The connector should also log the error but return 'bad credentials' (`next('bad credentials')`)

**Closed** 2016-09-09 10:36 UTC
Labels: enhancement
