### ISSUE TITLE
No error message when ID or Password is wrong

### ISSUE THREAD

**Issue by pierrevdk** [cozy-labs/konnectors#239] opened 2016-04-29 12:58 UTC
When adding a new service, if the ID or the password is wrong nothing happens. Their should be a message warning the user that the connexion can't be made because of a wrong id/password.

**Comment by nicofrand** [comment] 2016-07-20 14:00
Duplicate of https://github.com/cozy-labs/konnectors/issues/163 ?

**Comment by pierrevdk** [comment] 2016-07-22 08:44
@nicofrand Yes it is ;)

**Closed** 2016-07-22 08:46 UTC
Labels: bug
