### ISSUE TITLE
Lost fields

### ISSUE THREAD

**Issue by jsilvestre** [cozy-labs/konnectors#38] opened 2015-02-16 08:04 UTC
I enabled auto-import, and I am constantly losing encrypted fields...

**Comment by frankrousseau** [comment] 2015-03-08 15:23
The error is still here when an error occurs.

**Comment by jsilvestre** [comment] 2015-03-24 08:21
It happens every time the data system restarts for me.

**Comment by bnjbvr** [comment] 2015-05-07 07:27
I think I am experiencing this issue as well: sometimes, I get the notification that there was an error when importing data (from github commits, for instance), after a restart of the entire system. Giving it a look in the data browser shows me that the password field of the connector got reset somehow. Is it the same issue?

**Comment by jsilvestre** [comment] 2015-05-07 07:34
It is indeed, I didn't have time to check it out yet.

**Comment by ZeHiro** [comment] 2015-05-21 05:33
If seems to come from the used version of 'ware'. When upgrading to 1.3.0 (the last one), I can't reproduce anymore, whereas with version 0.3.0, the one used in 0.2.8 of konnectors, this bug was easily reproduceable : use bad credential and the password was deleted.

**Comment by eravion** [comment] 2015-06-30 08:54
Hello,
I configured my twitter account and after a reboot the credential is lost.
I don't have the problem with free or Bouygues Telecom invoice.

My feedback to push the topic ;)

**Comment by bnjbvr** [comment] 2015-06-30 08:58
Same here with Github commit. My girlfriend has the same issue with Withings. Please please, pretty please.

**Comment by clochix** [comment] 2015-07-08 08:14
@eravion [just mentioned](https://forum.cozy.io/t/konnector-impossible-de-demarrer-v-0-3-1-solved/902/8) in forum that latest refactoring of Konnectors seems to have fixed this issue. @jsilvestre, @bnjbvr, @ZeHiro could you give it a try and confirm ? Thanks !

**Comment by ZeHiro** [comment] 2015-07-08 08:44
It's been a long time since the last time I saw the problem (using Free, Free Mobile, and Github commits konnectors)

**Comment by bnjbvr** [comment] 2015-07-08 08:50
Seems fixed on my cozy, after reinstalling Konnectors + restarting the instance. Thanks!

**Comment by eravion** [comment] 2015-07-08 18:42
For twitter, it's different issue now.
The credential are not removed, but twitter Konnector still have "credential error" after the reboot.
Click on the "Save and Import" button force a new connection and fix the problem.

From my point of view, the problem looks partially fixed.

**Comment by ZeHiro** [comment] 2015-07-30 11:32
Could this problem be linked with https://github.com/cozy/cozy-data-system/issues/153
?

**Comment by frankrousseau** [comment] 2016-05-12 17:54
It looks to be solved, I close the issue.

**Closed by frankrousseau** 2016-05-12 17:54 UTC
Labels: 0 - Backlog, bug
