### ISSUE TITLE
Ameli wrong url

### ISSUE THREAD

**Issue by rgarrigue** [cozy-labs/konnectors#246] opened 2016-05-04 14:04 UTC
Hi

I'm running cozy under Raspbian Jessie. My ameli konnector didn't worked, with the following error in konnector.log (and less in konnector.err)

    [2016-05-04 12:04:30:548] info - Ameli | import for entry 042016 started.
    [Error: Cannot download file, wrong url]
    [2016-05-04 12:04:30:964] info - Ameli | File for 042016 not created.
    [2016-05-04 12:04:31:610] error - Ameli | An error occured while creating file
    [Error: Cannot download file, wrong url]

With @clochix and @ZeHiro help, I added some debug intel to grab more intel

    [Wed, 04 May 2016 13:37:55 GMT] - GET / - 200 - 2355.608 ms -  20199
    [Wed, 04 May 2016 13:38:13 GMT] - PUT /konnectors/45cac8a3683a2476446fca04b405db99 - 200 - 276.326 ms -  16
    [2016-05-04 14:38:13:878] info - ameli: Next update 11/05/2016 at 14:38:13
    [Wed, 04 May 2016 13:38:14 GMT] - GET /konnectors/45cac8a3683a2476446fca04b405db99 - 200 - 92.003 ms -  435
    [Wed, 04 May 2016 13:38:14 GMT] - GET /konnectors/45cac8a3683a2476446fca04b405db99 - 200 - 338.880 ms -  435
    [Wed, 04 May 2016 13:38:14 GMT] - GET /konnectors/45cac8a3683a2476446fca04b405db99 - 200 - 66.789 ms -  435
    [2016-05-04 14:38:17:46] info - Ameli | import for entry 042016 started.
    [Error: Cannot download file, url is https://assure.ameli.fr/PortailAS/PDFServletDetailPaiementRS.dopdf?idPaiement=0000000000000|P|0000000000000|0000000000000|0000000000000|null|A|U|, res is undefined, err is Error: CERT_UNTRUSTED, body is undefined]
    [2016-05-04 14:38:17:310] info - Ameli | File for 042016 not created.
    [2016-05-04 14:38:17:712] error - Ameli | An error occured while creating file
    [Error: Cannot download file, url is https://assure.ameli.fr/PortailAS/PDFServletDetailPaiementRS.dopdf?idPaiement=0000000000000|P|0000000000000|0000000000000|0000000000000|null|A|U|, res is undefined, err is Error: CERT_UNTRUSTED, body is undefined]

Turned out Raspbian Jessie doesn't trust ameli cert, seems it's been fixed in konnector but not in file. Adding `strictSSL: false,` around line 133 in `/usr/local/cozy/apps/konnectors/build/server/models/file.js` fixed it for now.

**Comment by nono** [comment] 2016-05-04 14:10
Looks like a duplicate of #216

**Comment by clochix** [comment] 2016-07-18 16:40
Hi @rgarrigue,

Do you still face this issue? The related #216 has been fixed for some time now…

**Comment by rgarrigue** [comment] 2016-07-21 20:36
Sorry, can't say as I nuked my cozy with an hazardous couchbase moving unto
usb drive... you can close the issue.

2016-07-18 18:40 GMT+02:00 Clochix <notifications@github.com>:

**Closed** 2016-07-22 15:35 UTC
Labels: bug
