### ISSUE TITLE
Connection to Ameli fails when the SS# contains the control key

### ISSUE THREAD

**Issue by brouberol** [cozy-labs/konnectors#221] opened 2016-03-31 08:53 UTC
When I first tried to configure the Ameli connector, I received some "bad credentials" message, even though I copy/pasted the username/password from the firefox password manager.

The connection then worked when I removed the last 2 digits of my social security number (the control key). Is that the expected behaviour? If that's the case, maybe the connector could strip the control key from the SS number automatically, to ease the connection process?

Cheers

**Comment by frankrousseau** [comment] 2016-03-31 08:54
Thank you @brouberol for reporting

@Gara64 Any thoughts?

**Comment by Gara64** [comment] 2016-03-31 09:01
@brouberol, it is indeed the expected behaviour. The Ameli login is your social security number, without the last 2 digits.
I think you're right that it could be confusing (it was for me the first time I logged into Ameli!), so an additional check could be done, at least to inform about the expected digit's number.
I'll work on it when I have some time :)

**Comment by brouberol** [comment] 2016-03-31 09:35
Ok, nice  to know :) I guess the Ameli website has some kind of
flexibility in the login then, because I can login with the SS# +
control key as my username.
 
--
B
 
 
On Thu, Mar 31, 2016, at 11:01 AM, Paul Tran-Van wrote:
> @brouberol[1], it is indeed the expected behaviour. The Ameli login is
> your social security number, without the last 2 digits.
>  I think you're right that it could be confusing (it was for me the
>  first time I logged into Ameli!), so an additional check could be
>  done, at least to inform about the expected digit's number.
>  I'll work on it when I have some time :)
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[2]
>
 

Links:

  1. https://github.com/brouberol
  2. https://github.com/cozy-labs/konnectors/issues/221#issuecomment-203833783

**Comment by frankrousseau** [comment] 2016-05-24 20:30
@brouberol It looks like @doubleface made a fix for this. Can you check that eveything is ok?

**Comment by brouberol** [comment] 2016-05-25 06:59
Seems to work, yes :)
 
--
B
 
 
On Tue, May 24, 2016, at 11:05 PM, Frank Rousseau wrote:
> @brouberol[1] It looks like @doubleface[2] made a fix for this. Can
> you check that eveything is ok?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[3]
>

Links:

  1. https://github.com/brouberol
  2. https://github.com/doubleface
  3. https://github.com/cozy-labs/konnectors/issues/221#issuecomment-221392071

**Comment by frankrousseau** [comment] 2016-05-25 08:54
Awesome thank you @brouberol and @doubleface!

**Closed by frankrousseau** 2016-05-25 08:54 UTC
Labels: bug
