### ISSUE TITLE
Several server errors

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#160] opened 2015-10-16 11:42 UTC
Hi,

Here are the errors I get in my logs (v 0.4.5): 
At import of free or free mobile bills: 
```
Error: Server error occured.
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/lib/cozymodel.js:110:27
    at parseBody (/usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
Error: Server error occured.
```

**Comment by frankrousseau** [comment] 2015-10-16 16:38
Hi @ZeHiro,

Thank you for the report. When have you started noticing that messages?

**Comment by ZeHiro** [comment] 2015-10-17 10:21
Minimum after 9/10 (date of log-backup) More surely after 14/10

**Comment by frankrousseau** [comment] 2015-10-22 18:26
Sorry I can't reproduce. Can you provide more details?

**Comment by ZeHiro** [comment] 2015-10-23 07:59
Could this be related to the fact that the password are lost?

**Comment by frankrousseau** [comment] 2015-10-23 11:05
Yes probably. Can you disconnect from Cozy. Log in again then restart (stop and start) the konnector application. Then try again?

**Comment by ZeHiro** [comment] 2015-10-23 12:56
I did what you say, and i cannot observe the error anymore.

**Comment by frankrousseau** [comment] 2015-11-08 22:01
Great, thank you. The problem is related to the Data System. Let close this issue.

**Closed by frankrousseau** 2015-11-08 22:01 UTC
